SELECT PLUS.PLUSVAL - MINUS.MINUSVAL AS BALANCE
FROM
	(SELECT COALESCE(SUM(AMOUNT),0) AS PLUSVAL
		FROM TRANSFERS
		WHERE TYPE IN ('Savings', 'Other', 'Cumulation') AND child_id = '465h546h' ) AS PLUS,
	(SELECT COALESCE(SUM(AMOUNT),0) AS MINUSVAL
		FROM TRANSFERS
		WHERE TYPE IN ('Withdraw', 'Deduction') AND child_id = '465h546h' ) AS MINUS